Repository hms-dbmi/pic-sure-gic-common-frontend, pull requests merged in 2023-09, with the labels that each got.

#58 [ALS-4906] Add Variant Explorer in GIC Common Area
  custom-migrations/auth/V19__VARIANT_EXPLORER.sql
  ui/src/main/webapp/picsureui/overrides/output/commonAreaVariantExpl.hbs
  ui/src/main/webapp/picsureui/overrides/output/outputPanel.hbs
  ui/src/main/webapp/picsureui/overrides/output/requestError.hbs
  ui/src/main/webapp/picsureui/overrides/output/variantExplorer.js
  ui/src/main/webapp/picsureui/overrides/styles.css
Labels: enhancement

#59 [ALS-4906] - Small fix to header
  ui/src/main/webapp/picsureui/overrides/output/variantExplorer.js
Labels: ignore-for-release

#62 [ALS-0000] Release hardening
  custom-migrations/auth/V18__UPDATE_TERMS_OF_SERVICE_2023.sql
  ui/src/main/webapp/picsureui/overrides/output/outputInfoModal.hbs
  ui/src/main/webapp/picsureui/overrides/output/variantExplorer.js
Labels: bug

#64 [ALS-5004] Help page tweeks
  ui/src/main/images/cool-science-stuff.png
  ui/src/main/webapp/picsureui/help/help-page.hbs
Labels: enhancement

#66 Update the query and model variables to use the model.
  ui/src/main/webapp/picsureui/overrides/package-data-view.js
Labels: enhancement

#68 Feature/genomic auto completer
  pic-sure-search-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRS.java
  pic-sure-search-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRSTest.java
  ui/src/main/webapp/picsureui/overrides/styles.css
Labels: invalid, ignore-for-release

#65 [ALS-4918] Add genomic auto-completer to common area search
  pic-sure-search-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRS.java
  pic-sure-search-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRSTest.java
  ui/src/main/webapp/picsureui/overrides/genomic-filter-view.js
  ui/src/main/webapp/picsureui/overrides/output/outputPanel.hbs
  ui/src/main/webapp/picsureui/overrides/styles.css
Labels: enhancement
