Repository hms-dbmi/pic-sure-gic-common-frontend, pull requests merged in 2023-11, with the labels that each got.

#82 [ALS-4773] Update to dataset view overrides
  ui/src/main/webapp/picsureui/overrides/dataset/dataset-manage.js
  ui/src/main/webapp/picsureui/overrides/dataset/dataset-save.hbs
  ui/src/main/webapp/picsureui/overrides/dataset/dataset-save.js
  ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.hbs
  ui/src/main/webapp/picsureui/overrides/dataset/dataset-view.js
  ui/src/main/webapp/picsureui/overrides/styles.css
Labels: enhancement

#84 [ALS-5334] Correct vaf description
  ui/src/main/webapp/picsureui/overrides/genomic-filter-view.js
Labels: bug

#86 [ALS-0000] Fix request access button on package data modal.
  ui/src/main/webapp/picsureui/overrides/package-data-view.js
Labels: bug

#85 [ALS-5283] GIC: Take a Tour
  ui/src/main/webapp/picsureui/header/header.hbs
  ui/src/main/webapp/picsureui/overrides/output/outputPanel.hbs
  ui/src/main/webapp/picsureui/overrides/router.js
  ui/src/main/webapp/picsureui/overrides/styles.css
  ui/src/main/webapp/picsureui/tour/tour.json
Labels: enhancement

#88 Add filter to remove undefined array items after flatten.
  ui/src/main/webapp/picsureui/overrides/dataset/utilities.js
Labels: bug

#87 Update text in tour.json
  ui/src/main/webapp/picsureui/tour/tour.json
Labels: ignore-for-release
