Repository hms-dbmi/pic-sure-gic-common-frontend, pull requests merged in 2024-01, with the labels that each got.

#91 [ALS-5510] Update dep versions
  pic-sure-query-uuid-resource/pom.xml
  pic-sure-search-resource/pom.xml
Labels: dependencies, ignore-for-release

#92 [ALS-0000] Add enhancements to releases
  .github/release.yml
  .github/workflows/label-checker.yml
Labels: ignore-for-release

#93 Make search resource compile
  pic-sure-search-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRS.java
  pic-sure-search-resource/src/test/java/edu/harvard/hms/dbmi/avillach/resource/search/SearchResourceRSTest.java
  ui/src/main/webapp/picsureui/overrides/package-data-view.js
Labels: bug
